apiVersion: v1
kind: Service
metadata:
  name: python-v1
spec:
  type: LoadBalancer
  ports:
  - port: 5000  
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: python
    version: v1