name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'Application-Code/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'Application-Code/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to the Docker HUB Registry
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: |
       cd Application-Code
       docker build . --file ./Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/python-app:latest
    - name: Push to Docker HUB Registry
      run: docker push ${{ secrets.DOCKER_USERNAME }}/python-app:latest
    - name: Delete the Local Image Built
      run: docker rmi ${{ secrets.DOCKER_USERNAME }}/python-app:latest


