name: K8s manifest deployments
on:
  workflow_dispatch:
  
jobs:
  terraform-actions:
    name: Workflow
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@main
      
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v1
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
    - name: Setup Kube Config
      run: aws eks --region us-west-2 update-kubeconfig --name linkfire-eks-cluster
      
    - name: Login to the Docker HUB Registry
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Kubectl info
      run: kubectl version

        
