name: Terraform DESTROY
on:
  workflow_dispatch:
  
jobs:
  terraform-actions:
    name: Workflow
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@main

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1

    - name: Terraform Init
      id: init
      run: |
       cd K8s-Terraform-Code
       terraform init -backend-config="bucket=${{ secrets.STATE_BUCKET_NAME }}" -backend-config="key=${{ secrets.STATE_PATH }}"
       
    - name: Terraform Destroy
      id: Plan
      run: |
       cd K8s-Terraform-Code
       terraform destroy -auto-approve
